spring:
  redis:
    host: redis.xquare.app
    port: 6379
  cloud:
    gateway:
      default-filters:
        - name: CustomGlobalAuthFilter
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowCredentials: false
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
              - GET
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: client-portal-user
          uri: ${USER_URL}
          predicates:
            - Path=/user/**,/admin/auth
            - Method=POST,OPTIONS,GET,DELETE,PUT,PATCH
        - id: client-portal-application
          uri: ${APPLICATION_URL}
          predicates:
            - Path=/application/**,/graduation/**,/score/**,/admin/application/**,/schools/**,/files/**,/pdf/**,/pass/**
            - Method=POST,OPTIONS,GET,DELETE,PUT,PATCH
        - id: client-portal-schedule
          uri: ${SCHEDULE_URL}
          predicates:
            - Path=/schedule/**
            - Method=POST,OPTIONS,GET,DELETE,PUT,PATCH
        - id: client-portal-feed
          uri: ${FEED_URL}
          predicates:
            - Path=/faq/**,/question/**,/notice/**,/reply/**,/attach-file/**
            - Method=POST,OPTIONS,GET,DELETE,PUT,PATCH
        - id: client-portal-status
          uri: ${STATUS_URL}
          predicates:
            - Path=/admin/status/**
            - Method=POST,OPTIONS,GET,DELETE,PUT,PATCH

  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: health, refresh, busrefresh
      base-path: /
      path-mapping:
        health: /
server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.server: DEBUG
