spring:
  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: health, refresh, busrefresh
      base-path: /
      path-mapping:
        health: /
server:
  port: 8888

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.server: DEBUG