spring:
  redis:
    host: entry-redis
    port: 6379
  cloud:
    gateway:
      default-filters:
        - name: CustomGlobalAuthFilter
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowCredentials: false
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
              - GET
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: client-portal-user
          uri: ${CASPER_USER_URL:https://casper-user.entrydsm.hs.kr}
          predicates:
            - Path=/user/**,/admin/**,/api/**,/test/**
            - Method=POST,OPTIONS,GET,DELETE,PUT,PATCH
        - id: client-portal-application
          uri: ${CASPER_APPLICATION_URL:https://casper-application.entrydsm.hs.kr}
          predicates:
            - Path=/application/**,/graduation/**,/score/**,/admin/application/**,/schools/**,/files/**,/pdf/**,/pass/**
            - Method=POST,OPTIONS,GET,DELETE,PUT,PATCH
        - id: client-portal-schedule
          uri: ${CASPER_SCHEDULE_URL:https://casper-schedule.entrydsm.hs.kr}
          predicates:
            - Path=/schedule/**
            - Method=POST,OPTIONS,GET,DELETE,PUT,PATCH
        - id: client-portal-feed
          uri: ${CASPER_FEED_URL:https://casper-feed.entrydsm.hs.kr}
          predicates:
            - Path=/faq/**,/notice/**,/attach-file/**,/screen/**,/reserve/**
            - Method=POST,OPTIONS,GET,DELETE,PUT,PATCH
        - id: client-portal-status
          uri: ${CASPER_STATUS_URL:https://casper-status.entrydsm.hs.kr}
          predicates:
            - Path=/admin/status/**,/internal/status/**
            - Method=POST,OPTIONS,GET,DELETE,PUT,PATCH

  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: health, refresh, busrefresh
      base-path: /
      path-mapping:
        health: /
server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.server: DEBUG
