spring:
  cloud:
    default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
    globalcors:
      cors-configurations:
        '[/**]':
          allowedOrigins:
            - 'http://localhost:3000'
            - 'http://localhost:3001'
            - 'http://localhost:3002'
          allow-credentials: true
          allowedHeaders: '*'
          allowedMethods:
            - PUT
            - GET
            - POST
            - DELETE
            - OPTIONS
  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: health, refresh, busrefresh
      base-path: /
      path-mapping:
        health: /
server:
  port: 8888